# Generated by Django 4.2.1 on 2023-06-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_remove_cartitem_product_remove_cartitem_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilepouch',
            name='offer_price',
        ),
    ]
